name: rtmp-webrtc-adapter-cicd

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Docker build & publish
      uses: docker/build-push-action@v1
      with:
        username: "${{ secrets.DOCKER_USERNAME }}"
        password: "${{ secrets.DOCKER_PASSWORD }}"
        registry: registry.cn-beijing.aliyuncs.com
        repository: mengli/rtmp-webrtc-adapter
        tags: latest

